[package]
name = "dav"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8"
directories = "5"
serde = { version = "1", features = [ "derive" ] }
tokio = { version = "1", features = [ "full" ] }
tracing = "0.1"
tracing-subscriber = "0.3"
